### ISSUE TITLE
No valid Data Response for collectd Container

### ISSUE THREAD

**Issue by ertan-goenuelal** [jonasrosland/collectd-ecs#2]
Seems that the Section `data = response.json()` doesnt get the the right Answer.
I get following Error Message during starting the collectd Container:
`
influxdb_1 | [run] 2017/04/13 11:30:11 Listening for signals
collectd_1 | exec plugin: exec_read_one: error = Traceback (most recent call last):
collectd_1 | exec plugin: exec_read_one: error =   File "/usr/bin/collect-ecs.py", line 33, in <module>
collectd_1 | exec plugin: exec_read_one: error =     data = response.json()
collectd_1 | exec plugin: exec_read_one: error =   File "/usr/lib/python2.7/site-packages/requests/models.py", line 866, in json
collectd_1 | exec plugin: exec_read_one: error =     return complexjson.loads(self.text, **kwargs)
collectd_1 | exec plugin: exec_read_one: error =   File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
collectd_1 | exec plugin: exec_read_one: error =     return _default_decoder.decode(s)
collectd_1 | exec plugin: exec_read_one: error =   File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
collectd_1 | exec plugin: exec_read_one: error =     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
collectd_1 | exec plugin: exec_read_one: error =   File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
collectd_1 | exec plugin: exec_read_one: error =     raise ValueError("No JSON object could be decoded")
collectd_1 | exec plugin: exec_read_one: error = ValueError: No JSON object could be decoded
`

If i do an curl with the X-SDS-AUTH-TOKEN it works. 
curl -L --location-trusted https://IP:4443/dashboard/zones/localzone/ -k -H "X-SDS-AUTH-TOKEN: EXAMPLETOKEN="

This Token is added to emcecs-config.yml.
Any Tips how i can verfy whats wrong with the json response that collect-ecs.py gets?

**Comment by jonasrosland** [comment]
Sorry for the delayed response @ertan-goenuelal. I don't have an environment to test this right now, so please keep me updated if there are any changes that needs to be done.
